quiz/urls.py
from django.urls import path

from . import views
#from dashboard .views import create_quiz,create_question
from quiz.views import  CustomerNumJsonView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'quiz'
urlpatterns = [
    # ex: /quiz/
    path('', views.index, name='index'),
    path('json',CustomerNumJsonView.as_view(),name="customers_json"),
    # ex: /quiz/5/
    path('<int:quiz_id>/', views.single_quiz, name='single_quiz'),

    # ex: /quiz/5/3/
    path('<int:quiz_id>/<int:question_id>/', views.single_question, name='single_question'),

    # ex: /quiz/5/3/vote/
    path('<int:quiz_id>/<int:question_id>/vote/', views.vote, name='vote'),

    # ex: /quiz/5/results/
    path('<int:quiz_id>/results/', views.results, name='results'),

    # # ex: /quiz/create/
    # path('create/', create_quiz, name='create_quiz'),

    # # ex: /quiz/create/7/2/
    # path('create/<int:quiz_id>/<int:question_id>/', create_question, name='create_question'),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quizup/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quizapp.urls')),
    path('quiz/', include('quiz.urls')),
    path('members/',include('django.contrib.auth.urls')),
    path('members/',include('members.urls')),
    path('dashboard/',include('dashboard.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quiz/models.py
from django.db import models


# Create your models here.
class Quiz(models.Model):
    quiz_title = models.CharField(max_length=300)
    num_questions = models.IntegerField(default=0)

    def __str__(self):
        return self.quiz_title


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=300)
    question_num = models.IntegerField(default=0)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=300)
    correct = models.BooleanField(default=False)

    def __str__(self):
        return self.choice_text

quiz/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

# form to create a new quiz
class CreateQuizForm(forms.Form):
    quiz_name = forms.CharField(max_length=50, label="Quiz Name", widget=forms.TextInput(attrs={'class': 'quiz_name_box'}))
    num_questions = forms.IntegerField(label="Number of Questions", widget=forms.NumberInput(attrs={'class': 'num_questions_box'}))

    def clean_name(self):
        data = self.cleaned_data['quiz_name']

        # Check if quiz name is unique.
        if data == "Default_Name":
            raise ValidationError(_('Invalid name - Must be Unique'))

        # returns cleaned data
        return data

    def clean_num_questions(self):
        data = self.cleaned_data['num_questions']

        # Check if number of questions is at least 1 and is an integer
        if (isinstance(data, int) == False) or (data < 1):
            raise ValidationError(_('Invalid number - must be positive integer'))

        # Remember to always return the cleaned data.
        return data


# form to create questions with choices for each quiz
class CreateQuestionForm(forms.Form):
    question_text = forms.CharField(max_length=300, label="Question Text", widget=forms.TextInput(attrs={'class': 'question_text_box'}))

    choice1_text = forms.CharField(max_length=300, label="Choice 1", widget=forms.TextInput(attrs={'class': 'choice_box'}))
    choice1_correctness = forms.BooleanField(label="Choice 1 Correct?", required=False, widget=forms.CheckboxInput(attrs={'class': 'choice_correct_box'}))

    choice2_text = forms.CharField(max_length=300, label="Choice 2", widget=forms.TextInput(attrs={'class': 'choice_box'}))
    choice2_correctness = forms.BooleanField(label="Choice 2 Correct?", required=False, widget=forms.CheckboxInput(attrs={'class': 'choice_correct_box'}))

    choice3_text = forms.CharField(max_length=300, label="Choice 3", widget=forms.TextInput(attrs={'class': 'choice_box'}))
    choice3_correctness = forms.BooleanField(label="Choice 3 Correct?", required=False, widget=forms.CheckboxInput(attrs={'class': 'choice_correct_box'}))

    choice4_text = forms.CharField(max_length=300, label="Choice 4", widget=forms.TextInput(attrs={'class': 'choice_box'}))
    choice4_correctness = forms.BooleanField(label="Choice 4 Correct?", required=False, widget=forms.CheckboxInput(attrs={'class': 'choice_correct_box'}))

    # makes sure that exactly one answer is selected to be true
    def clean(self):

        choice1_answer = self.cleaned_data["choice1_correctness"]
        choice2_answer = self.cleaned_data["choice2_correctness"]
        choice3_answer = self.cleaned_data["choice3_correctness"]
        choice4_answer = self.cleaned_data["choice4_correctness"]

        answer_list = [choice1_answer, choice2_answer, choice3_answer, choice4_answer]

        print(answer_list)

        trueCount = 0
        for answer in answer_list:
            if answer == True:
                trueCount += 1

        if trueCount != 1:
            raise ValidationError(_('Must have exactly one correct answer'))

        return self.cleaned_data

quiz/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib import admin
from quizapp.models import UserQuizData, userColloction
from .models import Quiz, Question, Choice
from django.views.generic import View
from .forms import CreateQuizForm, CreateQuestionForm
from django.http import JsonResponse

from django.db.models import Sum,Count
# Create your views here.
class CustomerNumJsonView(View):
    def get(self, *args, **kwargs):
        customer_count = UserQuizData.objects.filter(correct=True).count()

        return JsonResponse({'customer_count': customer_count})
# index page of all quizzes


def index(request):
    all_quiz_list = Quiz.objects.all()
   
  
    if request.user.is_authenticated:
        # duplicates = UserQuizData.objects.values('question_id').annotate(name_count=Count('question_id')).filter(name_count__gt=1)
        # records = UserQuizData.objects.filter(user_id=request.user,question_id__in=[item['question_id'] for item in duplicates])
        # show_presentation_list = []
        # menus_presentation = []
         # menus_presentation.append(menu)
        # for menu in records:
        #     if menu.question_id and menu.question_id in duplicates:
        #         attemt = userColloction(user_p=request.user, attempts=2)
        #         attemt.save()
        #         # show_presentation_list.append(menu.question_id)
        #         # menus_presentation.append(menu)
        #         print("yes")
        all_question = UserQuizData.objects.all()
        
        show_presentation_list = []
        menus_presentation = []
        for item in all_question:
            
            if request.user.id == item.user_id.id:
                if item.correct: 
                    show_presentation_list.append(item.question_id)
                    correct_answer = Choice.objects.filter(correct=True)
                    #for ite in correct_answer:
                    #if item.correct==correct_answer:
                        #correct_answer=correct_answer
                    
                
        
        total_points = userColloction.objects.filter(user_p=request.user).aggregate(Sum('user_points')).get('user_points__sum', 0.00) 
        context = {
            'all_quiz_list': all_quiz_list,
            
            'total_points':total_points,
            # 'records':records,
            #'correct_answer':correct_answer,
            'all_question':all_question,
            'show_presentation_list':show_presentation_list,
            'menus_presentation':menus_presentation
        }
    else:
         context = {
        
        'all_quiz_list': all_quiz_list,
    }
    # userl=userColloction.objects.filter(user_points__isnull=True).count()
    
   

    return render(request, 'quiz/index.html', context)


# specific quiz splash screen
def single_quiz(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    num_questions = len(quiz.question_set.all())
    #attemt=userColloction.objects.all()
    # member = userColloction(attempts=request.POST['attemptst'])
    # member.save()
    # deletes quiz and returns to home if no questions created
    if num_questions == 0:
        quiz.delete()
        all_quiz_list = Quiz.objects.all()
        context = {
            'all_quiz_list': all_quiz_list,
        }
        return render(request, 'quiz/index.html', context)

    quiz.num_questions = num_questions
    quiz.save()

    # resets accuracy info to 0
    request.session["num_correct"] = 0
    request.session["num_wrong"] = 0
    
    UserQuizData.objects.filter(user_id=request.user.id,q_category=quiz).delete()
    
                
    context = {
        'quiz': quiz,
        'num_questions': num_questions,
    }

    return render(request, 'quiz/single_quiz.html', context)

import random
# specific question view
def single_question(request, quiz_id, question_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    # forcount=list(Question.objects.filter(quiz=quiz_id))
    # random.shuffle(forcount)
    # suf=[]
    
    # for cc in forcount:
    #     if cc not in suf:
    #         suf.append(cc.question_num) 
    # for ss in suf:
    current_question = quiz.question_set.get(question_num=question_id)
    if request.user.is_authenticated:
        correct = UserQuizData.objects.filter(correct=True, user_id=request.user).count()
        wrong = UserQuizData.objects.filter(wrong=True, user_id=request.user).count()
        all_question = UserQuizData.objects.all()
        points=userColloction.objects.all()
    # Checks if currently on last  oquestionf quiz
    next_or_submit = "Next"
    last_question_check = False
    if question_id == (len(quiz.question_set.all())):
        last_question_check = True
        next_or_submit = "Submit"

    next_question_id = question_id+1

    all_choices = current_question.choice_set.all()
    if request.user.is_authenticated:
        context = {
            'current_question': current_question,
            'all_choices': all_choices,
            'quiz': quiz,
            'next_question_id': next_question_id,
            'last_question_check': last_question_check,
            'next_or_submit': next_or_submit,
            'all_question':all_question,
            'correct': correct,
            'wrong': wrong,
            'points':points,
            
        }
    else:
        context = {
            'current_question': current_question,
            'all_choices': all_choices,
            'quiz': quiz,
            'next_question_id': next_question_id,
            'last_question_check': last_question_check,
            'next_or_submit': next_or_submit,
            
        }
    return render(request, 'quiz/single_question.html', context)


# view that receives info from user's answer to question and determines correctness
def vote(request, quiz_id, question_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    current_question = quiz.question_set.get(question_num=question_id)
    title=Quiz.objects.all()
    
    # all_question = UserQuizData.objects.all()
    # all_question.delete()
    # all_questio = userColloction.objects.all()
    # all_questio.delete()
    # if title.quiz_title.id==current_question.id:
    #     quiz_title=title.id
    correct_answer = current_question.choice_set.get(correct=True)
    # checks if current question is last one
    next_or_submit = "Next"
    if question_id == (len(quiz.question_set.all())):
        next_or_submit = "Submit"

    try:
        selected_choice = current_question.choice_set.get(
            pk=request.POST['choice'])
            
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form
        return render(request, 'quiz/single_question.html', {
            'quiz': quiz,
            'current_question': current_question,
            'error_message': "You didn't select a choice.",
            'next_or_submit': next_or_submit,
            'correct_answer':correct_answer,
            'title':title
            
        
        })
    else:

        # get which choice is the correct answer
        correct_answer = current_question.choice_set.get(correct=True)

        if selected_choice == correct_answer:
            if request.user.is_authenticated:
                new_task = UserQuizData(user_id=request.user, question_id=current_question, correct=True, wrong=False,q_category=quiz)
                new_task.save()
                        
                adda = userColloction(user_p=request.user, user_points=+20,count=+1)
                adda.save()
                
                # if adda.user_points >= 20:
                #     levelu = userColloction(user_p=request.user, level=1)
                #     levelu.save()
                #     print("You are right")

            request.session["num_correct"] += 1
        else:
            if request.user.is_authenticated:
                new_task = UserQuizData(
                    user_id=request.user, question_id=current_question, correct=False, wrong=True,q_category=quiz)
                new_task.save()

            print("You are wrong")
            request.session["num_wrong"] += 1
            
            #menus_presentation.append(correct_answer)
            #return render(request, 'quiz/single_question.html', {'menus_presentation':menus_presentation})
            
        # checks if next page should be results or next question
        if question_id == (len(quiz.question_set.all())):
            return HttpResponseRedirect(reverse('quiz:results' ,args=(quiz.id,)))
            
        else:
            return HttpResponseRedirect(reverse('quiz:single_question', args=(quiz.id, question_id+1,)))


# quiz results page
def results(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    
    num_correct = request.session["num_correct"]
    num_wrong = request.session["num_wrong"]
    
    total_questions = num_correct+num_wrong

    # formats accuracy as % with no decimal digits
    accuracy = num_correct/(total_questions)

    accuracy_over_75 = False
    if accuracy >= .75:
        accuracy_over_75 = True

    accuracy_formatted = "{:.0%}".format(accuracy)
    if request.user.is_authenticated:
        
        correct = UserQuizData.objects.filter(correct=True, user_id=request.user,q_category=quiz).count()
        wrong = UserQuizData.objects.filter(wrong=True, user_id=request.user,q_category=quiz).count()
        all_question = UserQuizData.objects.all()
        points=userColloction.objects.all()
        context = {
            'num_correct': num_correct,
            'num_wrong': num_wrong,
            'accuracy_over_75': accuracy_over_75,
            'accuracy_formatted': accuracy_formatted,
            'total_questions': total_questions,
            'quiz': quiz,
            
            'all_question':all_question,
            'correct': correct,
            'wrong': wrong,

quiz/templates/quiz/index.html
{% extends 'base.html' %}
{% block content %}


{% load static %}

<!-- <link type="text/css" href="{% static 'quiz/index.css' %}" rel="stylesheet" > -->
<link rel="stylesheet" href="{% static 'quiz/index2.css' %}">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


<div class="area col-8 mx-auto text-white">
    <p></p>all_question
    {% for item in records %}
    {{item.question_id}}
    {% endfor %}
    
    {{user.id}}


    <!-- {{show_presentation_list}} -->
    {{menus_presentation}}
    {{correct_answer}}
    <!-- <p>total likeq  {{total}}</p>
        {% for quiza in userdatq %}
        <p>user:            {{quiza.user_id}}</p>
        <p>Question:            {{quiza.question_id}}</p>
        <p>Correct:            {{quiza.correct}}</p>
        <p>Wrong:            {{quiza.wrong}}</p>
        
        {% endfor %} -->
    <div class="text-white">
        <div id='counter'>0</div>
        <div id='customers'>customers</div>
    </div>
    
    <!-- {% for userp in userl %}
                        {% if user.id == userp.user_p.id %}
                            <h3 class="quiz_title">user points {{ userp.user_points }}</h3>
                            <p> user p{{ userp.user_p.id}}</p>
                            <p> user m{{ user.id}}</p>
                        {% endif %}  
                        </a>

                    {% endfor %} -->
    <div class="top_container">

    </div>

    {% if all_quiz_list %}

    <section class="card_container">

        {% for quiz in all_quiz_list %}
        <a class="card" href="{% url 'quiz:single_quiz' quiz.id %}">
            <h3 class="quiz_title">{{ quiz.quiz_title }}</h3>
            <h6 class="num_questions">{{ quiz.num_questions }} Questions</h6>
        </a>

        {% endfor %}
    </section>



    {% else %}
    <p>No quizzes are available.</p>
    {% endif %}

    <br>
    <br>
    <br>

</div>




{% endblock %}

quiz/templates/quiz/results.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<script src="{% static 'js/main2.js'  %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'quiz/results1.css' %}">

<meta charset="UTF-8">
<title>Results</title>

<div class="full_container col-8 mx-auto">

    <h1 class="results_title">Results</h1>
    <p class="correct_to_total">{{ num_correct }}/{{ total_questions }}</p>
    <p class="text-white">Wrong:&nbsp;{{num_wrong}}</p>
    <p class="text-white">Correct:&nbsp;{{num_correct}}</p>
    <p class="text-white">Wrong :&nbsp;{{wrong}}</p>
    <p class="text-white">Correct:&nbsp;{{correct}}</p>
    <p class="text-white"> Correct: answer: {{menus_presentation}}</p>
    <p class="text-white" id="UserAnswer"></p>
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        Check Result
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <table class="table">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Q:</th>
                                <th scope="col">Last</th>
                                <th scope="col">Points</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in all_question %}
                            {% if user.id == item.user_id.id and item.q_category.id == quiz.id %}
                            {% if item.correct %}
                            <tr class="alert alert-success" role="alert">
                                <th scope="row">{{item.id}}</th>
                                <td>{{item.question_id}}</td>
                                <td>{{item.correct}}</td>
                                {% for point in points %}
                                {% if user.id == point.user_p.id %}
                                {% if point.user_points %}
                                <td>{{point.user_points}}</td>
                                {% endif %}
                                {% endif %}
                                {% endfor %}
                            </tr>
                            {% endif %}
                            {% if item.wrong %}
                            <tr class="alert alert-danger" role="alert">
                                <th scope="row">{{item.id}}</th>
                                <td>{{item.question_id}}</td>
                                <td>False</td>
                                <td>0</td>
                            </tr>
                            {% endif %}
                            {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>





                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>

    {% if accuracy_over_75 %}
    <p class="accuracy_good">{{ accuracy_formatted }}</p>

    {% else %}
    <p class="accuracy_bad">{{ accuracy_formatted }}</p>
    {% endif %}

    <a class="home_button" href="{% url 'quiz:index' %}">Home</a>

    <a class="home_button" href="{% url 'quiz:single_quiz' quiz.id %}">Try Again</a>

</div>

{% endblock %}

quiz/templates/quiz/single_question.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% block scripts %}
<link rel="stylesheet" type="text/css" href="{% static 'quiz/single_question1.css' %}">


<link rel="stylesheet" type="text/css" href="{% static 'quiz/single_quiz1.css' %}">
{% endblock scripts %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<meta charset="UTF-8">
<title>Single Question</title>
<div class="full_container col-8 mx-auto text-white">
    <!-- <div id="timer-box">Timer</div> -->
    
    {% for data  in forcount  %}
      {{data}}
    {% endfor %}
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        Check Result
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <table class="table">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Q:</th>
                                <th scope="col">{{menus_presentation}}</th>
                                <th scope="col">Points</th>
                                
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in all_question %}
                            {% if user.id == item.user_id.id and item.q_category.id == quiz.id %}
                            {% if item.correct %}
                            <tr class="alert alert-success" role="alert">
                                <th scope="row">{{item.id}}</th>
                                <td>{{item.question_id}}</td>
                                <td>{{item.correct}}</td>
                                
                                {% for point in points %}
                                {% if user.id == point.user_p.id %}
                                {% if point.user_points %}
                                <td>{{point.user_points}}</td>
                                {% endif %}
                                {% endif %}
                                {% endfor %}
                            </tr>
                            {% endif %}
                            {% if item.wrong %}
                            <tr class="alert alert-danger" role="alert">
                                <th scope="row">{{item.id}}</th>
                                <td>{{item.question_id}}</td>
                                <td>False</td>
                                <td>0</td>
                            </tr>
                            {% endif %}
                            {% endif %}
                            {% endfor %}
                            
                            <div class="alert alert-danger" role="alert">
                                
                                <p>{{correct_answer}}</p>
                                
                            </div>
                            
                        </tbody>
                    </table>
                    
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>

    <h2 class="question_title text-white">{{ current_question.question_text }}</h2>
    {% for titles in title %}
    {% if current_question.id == titles.id%}
    <p class="text-white"> {{titles.id}}{{current_question.id}}</p>
    
    {% endif %}

    
    {% endfor %}
    {% if error_message %}
    <div class=" alert alert-warning" role="alert">{{ error_message }}</div>

    
    {% endif %}

    <form action="{% url 'quiz:vote' quiz.id current_question.question_num %}" method="post" class="text-white">
        {% csrf_token %}
        

        {% for choice in current_question.choice_set.all %}


        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" class="btn-check"  autocomplete="off" >
        <label class="btn btn-outline-success w-100 text-capitalize" for="choice{{ forloop.counter }}" >{{ choice.choice_text }}</label> <br>
        
        {% endfor %}
        <!-- <div class="radio-toolbar">

            {% for choice in current_question.choice_set.all %}

            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>


            {% endfor %}

        </div> -->

        <input type="submit" class="submit_button w-100" value='{{ next_or_submit }}' onclick="getanswer()">

    </form>

</div>
{% endblock %}

quiz/templates/quiz/single_quiz.html
{% extends 'base.html' %}
{% block content %}
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'quiz/single_quiz1.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script
    type="text/javascript"
    src="http://code.jquery.com/jquery-latest.min.js"
  ></script>

    <meta charset="UTF-8">
    <title>Single Quiz</title>


    <div class="full_container col-8 mx-auto my-3">

        <h1 class="quiz_title">{{ quiz.quiz_title }}</h1>

        <h4 class="num_questions">{{ num_questions }} Questions</h4>
<form action="" method="post">
    <a class="home_button" id="save" href="{% url 'quiz:single_question' quiz.id 1 %}">Start Quiz</a>
</form>
        
        <br>
        <br>
        <br>
        <a class="home_button"  href="{% url 'quiz:index' %}">Home</a>

    </div>

    <script type="text/javascript">
        //   $(function() {
        //     $("#save").on("click", function(e) {
        //       e.preventDefault();
        //       console.log("2")
        //       alert("radioValue =", radioValue);
        //       urls = "{% url 'quiz:single_question' quiz.id 1 %}",
        //       $.ajax({
                    // type: "POST",
                    // method: "POST",
        //         url: "{% url 'quiz:single_question' quiz.id 1 %}",
                
                
                
        //       })
               
        //     });
        //   });
        
    $('#save').on('click', function(){
        
        $attempt ="";
            $.ajax({
                type: "POST",
                url: "{% url 'quiz:single_question' quiz.id 1 %}",
                data:{
                    attemptst: $attempt+1,
                    
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                },
               
            });
           
    });

</script>
{% endblock %}