members/urls.py
from django.urls import path
from .views import PasswordsChangeView
from . import views
from django.conf import settings
from django.conf.urls.static import static

from .views import GeeksCreate
from .views import GeeksList
from .views import GeeksDetailView
from .views import GeeksUpdateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
app_name = 'members'
urlpatterns = [
    #path('register',UserRegistrationView.as_view() ,name='register'),
    path('register',views.register ,name='register'),
    path('login/', views.login_view, name ='login'),
    path('password/',PasswordsChangeView.as_view(template_name='registration/edit_password.html') ),
    path('success', views.success, name='success'),
   	  path('userdata', GeeksList.as_view(template_name = "base.html"),name="userdata"),
	path('add', GeeksCreate.as_view() ),
	
	path('profile/<int:pk>/', GeeksDetailView.as_view(template_name = "geeksmodel_detail.html"),name="profile"),
	 path('update/<pk>/', GeeksUpdateView.as_view(template_name = "geeksmodel_update.html"),name="update"),


    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/urls.py
from django.urls import path

from . import views
#from dashboard .views import create_quiz,create_question
from quiz.views import  CustomerNumJsonView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'quiz'
urlpatterns = [
    # ex: /quiz/
    path('', views.index, name='index'),
    path('json',CustomerNumJsonView.as_view(),name="customers_json"),
    # ex: /quiz/5/
    path('<int:quiz_id>/', views.single_quiz, name='single_quiz'),

    # ex: /quiz/5/3/
    path('<int:quiz_id>/<int:question_id>/', views.single_question, name='single_question'),

    # ex: /quiz/5/3/vote/
    path('<int:quiz_id>/<int:question_id>/vote/', views.vote, name='vote'),

    # ex: /quiz/5/results/
    path('<int:quiz_id>/results/', views.results, name='results'),

    # # ex: /quiz/create/
    # path('create/', create_quiz, name='create_quiz'),

    # # ex: /quiz/create/7/2/
    # path('create/<int:quiz_id>/<int:question_id>/', create_question, name='create_question'),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quizapp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import questionView
from quiz.views import index
urlpatterns = [
   path('', index,name='homepage'),
  # path('about', views.about,name='about'),
  path('about', views.about,name='about'),
    #path('about', questionView.as_view(),name='about'),
   path('contact', views.contact,name='contact'),
  # path('login', views.login,name='login'),
   path('home/', views.index,name='home')
   
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

quizup/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quizapp.urls')),
    path('quiz/', include('quiz.urls')),
    path('members/',include('django.contrib.auth.urls')),
    path('members/',include('members.urls')),
    path('dashboard/',include('dashboard.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quizapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime,date
from quiz.models import Question,Quiz
from members.models import User 
# Create your models here.
class Product(models.Model):
    
    question = models.CharField(max_length=200)
    option1 = models.TextField(blank=True, null=True)
    option2 = models.TextField(blank=True, null=True)
    option3 = models.TextField(blank=True, null=True)
    option4 = models.TextField(blank=True, null=True)
    answer = models.TextField(blank=True, null=True)


class UserQuizData(models.Model):
    user_id = models.ForeignKey(User,on_delete=models.CASCADE)
    question_id = models.ForeignKey(Question,on_delete=models.CASCADE)
    q_category= models.ForeignKey(Quiz,on_delete=models.CASCADE)
    correct=models.BooleanField()
    wrong=models.BooleanField()

    def __str__(self):
        return str(self.user_id)+  ' | ' + str(self.question_id )
    
class userColloction(models.Model):
    # user_level=models.CharField(max_length=250,blank=True,null=True)
    user_p= models.ForeignKey(User,on_delete=models.CASCADE)
    user_points=models.IntegerField(blank=True,null=True,default=0)
    #level=models.IntegerField(blank=True,null=True)
    count = models.IntegerField(blank=True, default=0)
    attempts=models.IntegerField(blank=True,default=0)
    def __str__(self):
            return str(self.user_p)+  ' | ' + str(self.user_points )
    def total_likes(self):
        return self.user_points.count()
    # def save(self, *args, **kwargs):
    #     self.count = self.user_points.count()
    #     super(User, self).save(*args, **kwargs)

quizapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Product,UserQuizData

from django.views.generic import ListView



class  questionView(ListView):
    
    mode=UserQuizData
    template_name='data.html'

def home(request):
	questionda = Product.objects.all()

	return render(request, 'index.html', { 'questionda': questionda})
def about(request):
    return render(request,'about.html')
def contact(request):
    return render(request,'contact_us.html')

def index(request):
    return render(request,'home.html')
# Create your views here.

quizapp/templates/about.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>about</h1>
    <div class="dropdown show">
        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown link
        </a>
      
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </div>
</body>
</html>
{% endblock %}

quizapp/templates/base.html
<!-- Example single danger button -->

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/fontawesome.min.js"></script>
  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <title>Document</title>
  <script src="https://kit.fontawesome.com/a076d05399.js"></script>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
 

</head>

<body>
 
  <div class="container-fluid ">
    <div class="row ">
      <div class="col-xl-2 col-lg-3  border">
        <div class="row ">
          <div class="col-xl-12 col-lg-12 col-md-3 col-sm-4 meanu-area">
            <nav class="navbar navbar-expand-lg navbar-light  flex-column">
              <a class="navbar-brand" href="#">
                <img src="{% static 'img/logo.png' %}" width="150" height="150" alt="">
              </a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse p-0 m-0" id="navbarNav">
                <ul class="navbar-nav  flex-column p-0 m-0">
                  <li class="nav-item shadow rounded my-2 border-bottom">
                    <a class="nav-link active text-white" href="{% url 'homepage' %}"><i class="fa fa-home"></i><span
                        class="mx-3">Home</span></a>
                  </li>
                  <li class="nav-item shadow rounded my-2 border-bottom">
                    <a class="nav-link text-white" href="about"><i class="fa fa-info-circle"
                        aria-hidden="true"></i><span class="mx-3">About Us</span></a>
                  </li>
                  <li class="nav-item shadow rounded my-2 border-bottom">
                    <a class="nav-link text-white" href="contact"><i class="fa fa-phone" aria-hidden="true"></i><span
                        class="mx-3">Contact Us </span></a>
                  </li>
                  <li class="nav-item shadow rounded my-2 border-bottom">
                    <a class="nav-link text-white" href="contact"><i class="fa fa-question" aria-hidden="true"></i><span
                        class="mx-3">FAQ </span></a>
                  </li>
                </ul>
                
              </div>
              <div class="col btnHover  p-0 m-0  social-icon ">
                <a href="#" class="fa fa-facebook"></a>
                <a href="#" class="fa fa-twitter"></a>
                <a href="#" class="fa fa-linkedin"></a>
              </div>
            </nav>
          </div>
        </div>
      </div>
      <div class="col-xl-10 col-lg-9 border m-0 p-0 ">
        
        {% if user.is_authenticated %}
      
        <div class="row bg-light top-area">
          
          <div class="col  btnHover border">
            
            <button type="button" class="btn btn-lg text-white  btn-block bg-transparent ">Points {{total_points}}</button>
          </div>
          <div class="col  btnHover border">
            <button type="button" class="btn btn-lg btn-block text-white  bg-transparent">Level</button>
          </div>
          <div class="col btnHover border">
            <div class=" d-flex justify-content-between py-3">
            
               
                <a href="{% url 'members:profile' user.id %} " class="text-capitalize text-white  "
                aria-hidden="true"><span class="mx-2 ">Profile</span></a>
              
              
              
              <a href="{% url 'logout' %}" class="fas fa-sign-out-alt text-white  "><span class="mx-2">logout</span></a>
  
            </div>
          </div>
        </div>
       
          
              
            
              
              
          
        
          
         
         
        {% else %}
        <div class="row  bg-light top-area ">
          
          <div class="col btnHover border">
            <div><button type="button" class="btn btn-lg btn-block text-white  bg-transparent">Normal</button></div>
          </div>
          <div class="col btnHover border">
            <div><button type="button" class="btn btn-lg btn-block text-white  bg-transparent ">Tournament</button></div>
          </div>
          <div class="col btnHover border">
            <div class=" d-flex justify-content-between py-3"><a href="{% url 'login' %}" class="fa fa-sign-in text-white  "
                aria-hidden="true"><span class="mx-2 ">Sign in</span></a>
              <a href="{% url 'members:register' %}" class="fas fa-sign-out-alt text-white  "><span class="mx-2">Sign up</span></a>
            </div>
          </div>
        </div>
        {% endif %}
        
        <div class="text-dark text-center quiz-area ">
          {% block content %}
          

        {% endblock %}

            
          
        </div>
      </div>
      <div class=" footer p-0 m-0 w-100 text-center text-white text-lg-start">
        <!-- Copyright -->
        <div class="text-center p-3">
          © 2020 Copyright:
          <a class="text-white" href="#">Quiz Up</a>
        </div>
        <!-- Copyright -->
      </div>
    </div>



  </div>
  

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
</body>

</html>

quizapp/templates/base2.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <title>{% block title %}
    main title

    {% endblock %}</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        {% if user.is_authenticated %}
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-capitalize" href="#" id="navbarDropdown" role="button"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ user.first_name }} {{ user.last_name }}
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% if user.profile.id %}
            <a class="dropdown-item" href="{% url 'show_profile_page' user.profile.id %}">Profile</a>
            {% else %}
            <a class="dropdown-item" href="{% url 'create_profile_page'  %}">Create Profile</a>
            {% endif %}
            <a class="dropdown-item" href="{% url 'logout' %}">logout</a>

        </li>


        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">Sign UP</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Sign in</a>
        </li>
        {% endif %}


       

        <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li>
      </ul>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        </ul>
    </div>
  </nav>

  <div class="container">
    {% block content %}


    {% endblock %}
  </div>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
</body>

</html>

quizapp/templates/contact_us.html
{% extends 'base.html' %}
{% block content %}



            <!--Grid column-->
            <div class="col-xl-8 col-lg-12 col-md-12 col-sm-12 mx-auto">

                <h2 class="h1-responsive font-weight-bold  mb-0 ">Got a Question?</h2>
                <!--Section description-->
                <p class=" w-responsive mx-auto mt-0 ">Is there something you can’t find an answer to or do you have something else you need help with? Let us know by filling out the form below!</p>

                <div class="row">

                    <!--Grid column-->
                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12  ">
                        <form id="contact-form" class="contact-form" name="contact-form" method="POST">

                            <!--Grid row-->
                            <div class="row">

                                <!--Grid column-->
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
                                    <div class="md-form mb-0">
                                        <input type="text" id="name" name="fname" class="form-control">
                                        <label for="name" class="">First name</label>
                                    </div>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
                                    <div class="md-form mb-0">
                                        <input type="text" id="name" name="lname" class="form-control">
                                        <label for="name" class="">Last name</label>
                                    </div>
                                </div>
                                <!--Grid column-->
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
                                    <div class="md-form mb-0">
                                        <input type="text" id="name" name="mobile" class="form-control">
                                        <label for="name" class="">Contact Number</label>
                                    </div>
                                </div>
                                <!--Grid column-->
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
                                    <div class="md-form mb-0">
                                        <input type="text" id="email" name="email" class="form-control">
                                        <label for="email" class="">Your email</label>
                                    </div>
                                </div>
                                <!--Grid column-->

                            </div>
                            <!--Grid row-->

                            <!--Grid row-->
                            <div class="row">
                                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                                    <div class="md-form mb-0">
                                        <textarea type="text" id="subject" name="subject" rows="2" class="form-control   md-textarea"></textarea>
                                        <label for="subject" class="">Subject</label>
                                    </div>
                                </div>
                            </div>
                            <!--Grid row-->

                            <!--Grid row-->
                            <div class="row">

                                <!--Grid column-->
                                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                                    <div class="md-form">
                                        <textarea type="text" id="message" name="message" rows="2" class="form-control   md-textarea"></textarea>
                                        <label for="message">Your message</label>
                                    </div>

                                </div>
                            </div>
                            <!--Grid row-->
                            <input type="submit" class="btn" name="register" value="Send Email" />
                        </form>

                        <div class="status"></div>
                    </div>
                    <!--Grid column-->

                </div>
            </div>
        
   
    
    {% endblock %}

quizapp/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block page_title %}{% endblock %}</title>


    <!-- add below Django command to use bootstrap3 in web page.  -->


    <!-- first load django static tag. -->
    {% load static %}
 
    <!-- use django static tag ton load js file and css file. -->
    <link rel="stylesheet" href="{% static 'css/index2.css' %}">

    

</head>
    <body>

        <div class="container">

            <!-- include web page navigation bar page -->
           


            {% block page_content %}
            <div class="hello"><h1>hello</h1></div>
            {% endblock %}

        </div>
    </body>
</html>

quizapp/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/fontawesome.min.js"></script>  
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/> 
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<title>login</title>
{% load static %}
	<style type="text/css">
* {
	margin: 0;
	padding: 0;
	font-family: sans-serif;
}

.top{
	height: 100%;
	width: 100%;
	background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),url("{% static 'img/bg.png' %}");
	background-position: center;
	background-size: cover;
	position: absolute;
}
.top-now{
	width: 380px;
	height: 520px;
	position: relative;
	margin: 6% auto;
	background-color: rgba(0,0,0,0.5);
	padding: 5px;
	overflow: hidden;
}
.top-up{
	width: 220px;
	margin: 35px auto;
	position: relative;
	box-shadow: 0 0 20px 9px #ff61241f;
	border-radius: 30px;
}
.btn{
	padding: 10px 30px;
	cursor: pointer;
	background: transparent;
	border: 0;
	outline: none;
	position: relative;
	color: white;
}
#btn1 {
	top: 0;
	left: 0;
	position:absolute;
	width:110px;
	height:100%;
	background: linear-gradient(to right, #ff105f,#1b2353);
	border-radius:30px;
	transition: 0.5s;

}
.s1{
	margin: 30px auto;
	text-align: center;
}

.form{
	color: white;
	top: 180px;
	position: absolute;
	width: 280px;
	transition: 0.5s;
}
.input{
	width: 100%;
	padding: 10px 0;
	margin: 5px 0;
	border-left: 0;
	border-top: 0;
	border-right: 0;
	border-bottom: 1px solid #999;
	outline: none;
	color: white;
	background: transparent;
}
.submit{
	width: 85%;
	padding: 10px 30px;
	cursor: pointer;
	display: block;
	margin:auto;
	background:linear-gradient(to right, #ff105f,#1b2353);
	border:0;
	outline: none;
	border-radius: 30px;
    color: white;
}
.checkbox{
	margin: 30px 10px 30px 0;
}
span{
	color: #777;
	font-size: 12px;
	bottom: 68px;
	position: absolute;
}
#login{
	left:50px;

}
#signup{
left: 450px;
}

.social-icon a.fa {
  padding: 7px;
    font-size: 20px;
    width: 39px;
    text-align: center;
    text-decoration: none;
    margin: 2px 2px;
    border-radius: 50%;
}
.social-icon a.fa:hover {
    opacity: 0.7;
}

.fa-facebook {
  background: #3B5998;
  color: white;
}

.fa-twitter {
  background: #55ACEE;
  color: white;
}
.fa-google {
  background: #e28052;
  color: rgb(255, 255, 255);
}
</style>
</head>
<body>

<div class="top">
	<div class="top-now">
		<div class="top-up d-flex">
			<div id="btn1"></div>
			<button type="button" class="btn" onclick="login()"> LOGIN</button>
			<button type="button" class="btn" onclick="signup()"> SIGNUP</button>
		</div>
	
        <div class="col btnHover  s1 py-2 social-icon ">
            <a href="#" class="fa fa-facebook"></a>
            <a href="#" class="fa fa-twitter"></a>
            <a href="#" class="fa fa-google"></a>
          </div>
	<form id="login" class="form">
		<input type="text" class="input"  placeholder="Your ID" required>
		<input type="text" class="input" placeholder="Enter Password" required>
		<input type="checkbox" class="checkbox"><span> Remember Password</span>
		<button type="submit" class="submit"> LogIn</button>
	</form>

	<form id="signup"  class="form">
		<input type="text" class="input" placeholder="Full Name" required>
		<input type="email" class="input" placeholder="Email ID" required>
		<input type="text" class="input" placeholder="Password" required>
		<input type="text" class="input" placeholder="Confirm Password" required>
		<input type="checkbox" class="checkbox"><span> I agree to the terms and Conditions</span>
		<button type="submit" class="submit"> SignUp</button>
	</form>



</div>

</div>
<script type="text/javascript">
	var x = document.getElementById("login")
	var y = document.getElementById("signup")
	var z = document.getElementById("btn1")
	function signup(){
		x.style.left= "-400px";
		y.style.left= "50px";
		z.style.left= "110px";
	}

	function login(){
		x.style.left= "50px";
		y.style.left= "450px";
		z.style.left= "0";
	}
</script>

</body>
</html>